// import Footer from "@/components/common/Footer";
import Header from "@/components/common/Header";
import "./globals.css";
import { Geist } from 'next/font/google';
import StoreProvider from "../app/StoreProvider";

const geist = Geist({
  subsets: ['latin'],
})

export const metadata = {
  title: "Nipralo Jira",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={geist.className}>
      <body>
        {/* Wrap the entire app with StoreProvider to make Redux store available */}
        <StoreProvider>
          <Header />
          {children}
          {/* <Footer /> */}
        </StoreProvider>
      </body>
    </html>
  );
}
